config/routes.rb
Rails.application.routes.draw do

  resources :campsites, only: [:index]  do
    resources :campers, only: [:index]
  end
  resources :campers, only: [:index] do
    resources :supplies, only: [:index]
  end

  resources :supplies, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/camper.rb
class Camper < ApplicationRecord
  belongs_to :campsite
  has_many :supplies
end

app/models/campsite.rb
class Campsite < ApplicationRecord
  has_many :campers
end

app/models/supply.rb
class Supply < ApplicationRecord
  belongs_to :camper
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campers_controller.rb
class CampersController < ApplicationController

  def index
    # binding.pry

    if params[:campsite_id].nil?
      @title = "All Campers:"
      @campers = Camper.all
    else
      campsite= Campsite.find(params[:campsite_id])
      @title= "Campers bunking in #{campsite.name}"
      @campers= campsite.campers
    end
  end

end

app/controllers/campsites_controller.rb
class CampsitesController < ApplicationController

  def index
    @title = "All Campsites:"
    @campsites = Campsite.all
  end

  def show
    @campsite= Campsite.find(params[:id])
  end
end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  def index
    binding.pry
    if params[:camper_id].nil?
      @title = "All Supplies:"
      @supplies = Supply.all
    else
      camper=Camper.find(params[:camper_id])
      @title= "Supplies Brought by #{camper.name}"
      @supplies=camper.supplies
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/campers/index.html.erb
<h1><%= @title %></h1>

<ul>
  <% @campers.each do |camper| %>
    <li>
      <%= link_to camper.name, camper_supplies_path(camper) %>
    </li>
  <% end %>
</ul>

app/views/campsites/index.html.erb
<h1><%= @title %></h1>

<ul>
  <% @campsites.each do |campsite| %>
    <li>
      <%= link_to campsite.name, campsite_campers_path(campsite) %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CampingTripRails</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/supplies/index.html.erb
<h1> <%= @title %> </h1>

<ul>
  <% @supplies.each do |supply| %>
    <li>
      <%= supply.name %>
    </li>
  <% end %>
</ul>